version: '3.7'

services:
    node:
        container_name: node
        build:
            context: .
            dockerfile: ./docker/node/Dockerfile
        volumes:
            - .:/home/node/app
            - ./node_modules:/home/node/app/node_modules
        working_dir: /home/node/app/
        # Allow container to execute gameservers on host machine
        privileged: true
        tty: true
        pid: host
        command: sh -c " pnpm install && pnpm run deploy-commands && pnpm run start"

    pocketbase:
        image: spectado/pocketbase:latest
        container_name: pocketbase
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./x_db_data:/pb_data

volumes:
    node_modules:
