version: '3.7'

services:
    ts-node:
        container_name: Node_${COMPOSE_PROJECT_NAME}
        image: node:${NODE_VERSION}
        volumes:
            - ./:${DOCUMENT_ROOT}
        working_dir: ${DOCUMENT_ROOT}
        # Allow container to execute gameservers on host machine
        privileged: true
        tty: true
        pid: host
        command: sh -c "
            npm install &&
            npm run deploy-commands && 
            npm run start
            "
